### ISSUE TITLE
clout incorrectly excludes ',' from allowed path characters

### ISSUE THREAD

**Issue by tcrayford** [weavejester/clout#23]
It looks like https://github.com/weavejester/clout/blob/master/src/clout/core.clj#L91 incorrectly excludes `,` from the characters it's willing to match in a path, given the characters allowed in a path (see http://stackoverflow.com/questions/4669692/valid-characters-for-directory-part-of-a-url-for-short-links/4669755#4669755 for one listing of such).

**Comment by weavejester** [comment]
A Clout parameter isn't the same thing as a path segment, so the default regular expression for a parameter isn't necessarily going to be the same thing either.

**Comment by tcrayford** [comment]
@weavejester : so I guess the suggested workaround here is to supply custom regexes for matching path segments that don't match up with the default path segments?

(btw this had customers hitting 404s on my app today - I was escaping parameters with `ring.util.codec/url-encode` and then generating urls that were invalid)

**Comment by weavejester** [comment]
A workaround implies that this is a bug, rather than an incorrect assumption. If you want a parameter to match a exactly match the definition of a path segment, then yes, you'll need to supply your own regular expression.
