### ISSUE TITLE
Old instaparse dependency

### ISSUE THREAD

**Issue by fraczak** [weavejester/clout#28]
Is is possible to upgrade to "instaparse 1.4.2"?

**Comment by weavejester** [comment]
Sure. Is 1.4.0 causing problems?

**Comment by fraczak** [comment]
Yes, as I use the new function add-line-and-column-info-to-metadata introduced in instaparse 1.4.1.

**Comment by weavejester** [comment]
Do you know that you can use Instaparse 1.4.2 and Clout in your project? Adding an Instaparse dependency of your own will override the one included by Clout.

**Comment by NoahTheDuke** [comment]
I think this can be closed
