### ISSUE TITLE
Routes with negative lookahead regex always return nil

### ISSUE THREAD

**Issue by BrianFanning** [weavejester/clout#29]
Hi there, I'm trying to create a route which has a regex with a negative lookahead, but I can't seem to get it to match any routes at all.

Basically I want to match all possible "/foo/:fragment" routes that do not contain "admin" in the fragment part. I defined a route like so:
```
(def user-route
  (clout/route-compile "/foo/:fragment" {:fragment #"^((?!admin).)*$"}))
```
However both the tests below return nil:
```
(clout/route-matches
  user-route
  (mock/request :get "/foo/user"))
=> nil

(clout/route-matches
  user-route
  (mock/request :get "/foo/admin"))
=> nil
```

I've tested this with simpler negative lookahead regexes and had the same result. I'd appreciate any help with this.

**Comment by weavejester** [comment]
Clout doesn't convert the regular expressions you use in any way, so `^` and `$` are not automatically removed, and matching groups are not automatically turned into non-matching groups.

You can see the problem if you take a look at the compiled route:

```clojure
#clout.core.CompiledRoute{
  :source "/foo/:fragment"
  :re #"/foo/(^((?!admin).)*$)"
  :keys [:fragment]
  :absolute? false}
```

See how your regular expression is inserted directly into the compiled regular expression that Clout produces? In order for your code to work, you need something more like:

```clojure
(def user-route
  (clout/route-compile "/foo/:fragment" {:fragment #"(?:(?!admin).)*"}))
```

This produces the result you want:

```clojure
(clout/route-matches user-route (mock/request :get "/foo/user"))
=> {:fragment "user"}
(clout/route-matches user-route (mock/request :get "/foo/admin"))
nil
```

**Comment by BrianFanning** [comment]
I should have looked at the compiled route... thanks for your help!

**Comment by weavejester** [comment]
No problem. It's not something that's immediately obvious, and it's a little bit of a leaky abstraction, because you have to bare in mind that the regular expressions for each keyword are substituted directly into the regular expression in the compiled route.
