### ISSUE TITLE
Recipe for matching query strings?

### ISSUE THREAD

**Issue by binarykitchen** [weavejester/clout#30]
Something like `(clout/route-compile "/api/verify?token=abc")` does not work. Is there a recipe, example and unit test for that?

**Comment by weavejester** [comment]
Clout doesn't match the query string, I'm afraid. You can just match "/api/verify" and then check the token exists in Compojure.

**Comment by binarykitchen** [comment]
mmmhh, thanks @weavejester, is there an example out in the wild for that?

**Comment by weavejester** [comment]
Sure. You could write it:

```clojure
(GET "/api/verify" [token]
  (when token ...))
```

Because if `token` is `nil`, the route returns `nil` and therefore the next route is tried. Alternatively:

```clojure
(GET "/api/verify" [token :<< identity]
  ...)
```

Coercions fail the route if they are `nil`, so by using the identity function as the coercion, we achieve the same effect as using `when`.

**Comment by binarykitchen** [comment]
yep, thanks but i rather meant an example where you are using clout for route matching and then compojure for query parameter parsing both.

**Comment by weavejester** [comment]
That *is* an example of using Clout for route matching. Compojure uses Clout.

**Comment by binarykitchen** [comment]
oh i see. learned. many thanks!
