### ISSUE TITLE
[SOLVED] java.lang.IllegalArgumentException: No implementation of method: :route-matches of protocol: #'clout.core/Route found for class: clout.core.CompiledRoute

### ISSUE THREAD

**Issue by unclechu** [weavejester/clout#34]
This is a reopen of: https://github.com/weavejester/clout/issues/27

Here are my dependencies:
``` clojure
 {org.clojure/clojure {:mvn/version "1.10.3"}
  org.clojure/tools.cli {:mvn/version "1.0.206"}
  http-kit/http-kit {:mvn/version "2.5.3"}
  compojure/compojure {:mvn/version "1.6.2"}
  }
```

I’m trying to make a separate build (as a NixOS derivation) where I kind of manually compile a couple of modules like this (without even using anything like `deps.edn`). I found an example here: https://stackoverflow.com/questions/29011295/compile-clojure-source-into-class-aot-from-command-line-not-using-lein#29012274

``` sh
          java -cp ${esc backend-classpaths}:"$src"/src \
            -Dclojure.compile.path=build \
            clojure.lang.Compile \
            "$module"
```

Where `${esc backend-classpaths}` is a list of JAR files of the dependencies described above and `"$src"/src` is where my source code is. Then I run it like this:

``` sh
      java -cp ${esc backend-classpaths}:${backendBuiltClasses} clojure_todo_app.main
```

Where `${backendBuiltClasses}` is a directory with those pre-built classes.

The application successfully starts, arguments get parsed, but when I do a test `curl` request I get this error:

> java.lang.IllegalArgumentException: No implementation of method: :route-matches of protocol: #'clout.core/Route found for class: clout.core.CompiledRoute

Any ideas what’s wrong?

I also found https://stackoverflow.com/questions/31129470/java-lang-illegalargumentexception-no-implementation-of-method-route-matches but in my case this isn’t useful.

**Comment by weavejester** [comment]
You have an older version of Clout in your classpath somewhere. Compojure is trying to use a newer version of Clout and failing because it doesn't support the same protocols.

**Comment by unclechu** [comment]
@weavejester,

Resulting command that runs it:

``` sh
exec '/nix/store/kriwzlgsm647ql2w6zb3xn4dj8nrfwaa-openjdk-16+36/bin/java' \
  -cp '/nix/store/681yqlj7x1d61szm5bj7nhk51j5dvyfl-org_clojure_clojure-1.10.3.jar:/nix/store/zy26l2asl2grn3kymqr22m7l8hfq7bbm-commons-codec_commons-codec-1.11.jar:/nix/store/9860d1cazd6jbfmz79hkm2r34l032qvd-org_clojure_core_specs_alpha-0.2.56.jar:/nix/store/ls91sp8kc4qb2xg87ab911030mi61zls-org_clojure_spec_alpha-0.2.194.jar:/nix/store/zc7f8zhv982jilwr9mgi9dw26a69jbg5-org_clojure_tools_cli-1.0.206.jar:/nix/store/9q2r7rbk6wnwlrc97j3pwdg091jabj1a-compojure_compojure-1.6.2.jar:/nix/store/x06s759g8xbd754s3v8y00s77abqqykr-commons-fileupload_commons-fileupload-1.4.jar:/nix/store/pqzqn0iz8hnqal77rx7s0dgvrsf55xak-org_clojure_tools_macro-0.1.5.jar:/nix/store/arj6l00babg1x8m9wagdxx7k7nc6yygc-commons-io_commons-io-2.6.jar:/nix/store/bly0fqjixsahq6rj1k1yvsm5xakzzigz-instaparse_instaparse-1.4.8.jar:/nix/store/m9ifhpy800vdkc1j6k65vkpprsr0195l-clout_clout-2.2.1.jar:/nix/store/sydc477788pky2zsxs70rqdm91ly3sgw-crypto-random_crypto-random-1.2.0.jar:/nix/store/88gq9wrz4yspc6hhwnvs5naf6v33an6w-ring_ring-codec-1.1.2.jar:/nix/store/zjk05j8p7mwr4bvsxbzsf4664myv66hj-crypto-equality_crypto-equality-1.0.0.jar:/nix/store/h8m2mh43m31vnmhxb5q45pkd8fbjpys1-ring_ring-core-1.8.1.jar:/nix/store/rj47ywnlgl0abxby05439l6biwq4rpnz-medley_medley-1.3.0.jar:/nix/store/ncsawsc90nww7rxzczyswk4j15w8zqxi-http-kit_http-kit-2.5.3.jar':/nix/store/1ssj6x352q1wp4mpkr20z3kbyanvj3x4-clojure-todo-app-built-classes \
  'clojure_todo_app.main' "$@"
```

That class path split into a list:

- `/nix/store/681yqlj7x1d61szm5bj7nhk51j5dvyfl-org_clojure_clojure-1.10.3.jar`
- `/nix/store/zy26l2asl2grn3kymqr22m7l8hfq7bbm-commons-codec_commons-codec-1.11.jar`
- `/nix/store/9860d1cazd6jbfmz79hkm2r34l032qvd-org_clojure_core_specs_alpha-0.2.56.jar`
- `/nix/store/ls91sp8kc4qb2xg87ab911030mi61zls-org_clojure_spec_alpha-0.2.194.jar`
- `/nix/store/zc7f8zhv982jilwr9mgi9dw26a69jbg5-org_clojure_tools_cli-1.0.206.jar`
- `/nix/store/9q2r7rbk6wnwlrc97j3pwdg091jabj1a-compojure_compojure-1.6.2.jar`
- `/nix/store/x06s759g8xbd754s3v8y00s77abqqykr-commons-fileupload_commons-fileupload-1.4.jar`
- `/nix/store/pqzqn0iz8hnqal77rx7s0dgvrsf55xak-org_clojure_tools_macro-0.1.5.jar`
- `/nix/store/arj6l00babg1x8m9wagdxx7k7nc6yygc-commons-io_commons-io-2.6.jar`
- `/nix/store/bly0fqjixsahq6rj1k1yvsm5xakzzigz-instaparse_instaparse-1.4.8.jar`
- `/nix/store/m9ifhpy800vdkc1j6k65vkpprsr0195l-clout_clout-2.2.1.jar`
- `/nix/store/sydc477788pky2zsxs70rqdm91ly3sgw-crypto-random_crypto-random-1.2.0.jar`
- `/nix/store/88gq9wrz4yspc6hhwnvs5naf6v33an6w-ring_ring-codec-1.1.2.jar`
- `/nix/store/zjk05j8p7mwr4bvsxbzsf4664myv66hj-crypto-equality_crypto-equality-1.0.0.jar`
- `/nix/store/h8m2mh43m31vnmhxb5q45pkd8fbjpys1-ring_ring-core-1.8.1.jar`
- `/nix/store/rj47ywnlgl0abxby05439l6biwq4rpnz-medley_medley-1.3.0.jar`
- `/nix/store/ncsawsc90nww7rxzczyswk4j15w8zqxi-http-kit_http-kit-2.5.3.jar`
- `/nix/store/1ssj6x352q1wp4mpkr20z3kbyanvj3x4-clojure-todo-app-built-classes`

The same classpath was used for compilation. By looking at `/nix/store/m9ifhpy800vdkc1j6k65vkpprsr0195l-clout_clout-2.2.1.jar` I can say the version is `2.2.1` which seems to be the latest.

I think this is also impossible that it fetched something older from the internet since in a Nix sandbox where it was built there is no internet. There is also no `*.edn` file in that sandbox so it couldn’t even guess the dependencies I guess to download anything.

Also here is a pin of the version:

``` nix
  rec {
    name = "clout/clout";
    src = fetchmaven {
      inherit repos;
      artifactId = "clout";
      groupId = "clout";
      sha512 = "99d6e1a8c5726ca4e5d12b280a39e6d1182d734922600f27d588d3d65fbc830c5e03f9e0421ff25c819deee4d1f389fd3906222716ace1eb17ce70ef9c5e8f4b";
      version = "2.2.1";
      
    };
    paths = [ src ];
  }
```

As expected, it’s the latest one.

Given these facts, I don’t think it is the case that it uses the older version of `clout`.

**Comment by unclechu** [comment]
Also, if I use the same sandbox and the same classpath and if I add source directory instead of a directory with pre-built classes (so I just skip any building step), it works just fine.

**Comment by weavejester** [comment]
Without more information about your build setup, or the stacktrace of the exception, I'm afraid I can't guess at why you have a version mismatch.

**Comment by unclechu** [comment]
@weavejester 

- The project https://github.com/unclechu/clojure-todo-app/tree/39bb8abbf05ad36ac85ce328c8d8419c83bd14dd — the commit is the state where I have compilation step.

- Step where I build the class files: https://github.com/unclechu/clojure-todo-app/blob/39bb8abbf05ad36ac85ce328c8d8419c83bd14dd/default.nix#L91-L106

- README where I describe how to build it (just run `nix-build`): https://github.com/unclechu/clojure-todo-app/blob/39bb8abbf05ad36ac85ce328c8d8419c83bd14dd/README.md

- List of pinned dependencies (that is resulting to classpath with JAR files): https://github.com/unclechu/clojure-todo-app/blob/39bb8abbf05ad36ac85ce328c8d8419c83bd14dd/backend/deps.nix

---

The full exception:

``` console
$ curl http://localhost:8080
No implementation of method: :route-matches of protocol: #'clout.core/Route found for class: clout.core.CompiledRoute
```

``` console
$ result/bin/clojure-todo-app-backend
Running HTTP server on port 8080…
Thu Nov 11 23:04:58 EET 2021 [worker-1] ERROR - GET /
java.lang.IllegalArgumentException: No implementation of method: :route-matches of protocol: #'clout.core/Route found for class: clout.core.CompiledRoute
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
        at clout.core$eval2486$fn__2487$G__2477__2494.invoke(core.cljc:51)
        at compojure.core$route_matches.invokeStatic(core.clj:46)
        at compojure.core$route_matches.invoke(core.clj:44)
        at compojure.core$route_request.invokeStatic(core.clj:49)
        at compojure.core$route_request.invoke(core.clj:48)
        at compojure.core$wrap_route_matches$fn__2976.invoke(core.clj:145)
        at compojure.core$routing$fn__2991.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2705)
        at clojure.core$some.invoke(core.clj:2696)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:662)
        at compojure.core$routes$fn__2995.invoke(core.clj:192)
        at org.httpkit.server.HttpHandler.run(RingHandler.java:117)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

---

But still, I have doubts that the version is outdated. Unless something wrong is pushed to or pulled from Maven repository.

**Comment by unclechu** [comment]
Sorry, I should have attached the stack trace earlier. I don’t know why I didn’t.

**Comment by weavejester** [comment]
It could also be a compilation issue if the class file for `CompiledRoute` is missing or from an outdated build. If you can give me the shell commands that are being executed I might be able to help. I don't want to install Nix just to diagnose this issue.

In any case, this doesn't appear to be an issue with Clout itself.

**Comment by unclechu** [comment]
@weavejester It cannot be from outdated build, it’s in a sandbox where everything is clean.

Okay, let’s try to reproduce. Here is a ZIP archive of all those JAR files from the list above: [deps-as-jars.zip](https://github.com/weavejester/clout/files/7523544/deps-as-jars.zip)

1. `git clone https://github.com/unclechu/clojure-todo-app reproduce-error`
1. `cd reproduce-error/`
1. `git checkout 39bb8abbf05ad36ac85ce328c8d8419c83bd14dd`
1. `unzip /path-to-that-zip-archive-from-above/deps-as-jars.zip`
1. ``` console
   $ java --version
   openjdk 16 2021-03-16
   OpenJDK Runtime Environment (build 16+36-nixos)
   OpenJDK 64-Bit Server VM (build 16+36-nixos, mixed mode, sharing)
   ```
1. `mkdir build`
1. `java -cp "$(find deps-as-jars/ | xargs | tr ' ' ':')":backend/src -Dclojure.compile.path=build clojure.lang.Compile clojure-todo-app.main`
1. `java -cp "$(find deps-as-jars/ | xargs | tr ' ' ':')":backend/src -Dclojure.compile.path=build clojure.lang.Compile clojure-todo-app.utils`
1. Now try to run:
   ``` console
   $ java -cp "$(find deps-as-jars/ | xargs | tr ' ' ':')":build clojure_todo_app.main
   Running HTTP server on port 8080…
   ```
1. In a separate terminal call
   ``` console
   $ curl http://localhost:8080
   hello world
   ```
   And it works :shrug: I have no clue why. Why it doesn’t if I build it sandboxed. Maybe I should try to remove the caches and turn off internet or something. Nix isolates the sandbox. With this test it can be taken from cache from my `HOME` or it can download stuff from the internet.

**Comment by unclechu** [comment]
No difference in file structure at least:
``` console
$ diff <(tree build/) <(tree /nix/store/1ssj6x352q1wp4mpkr20z3kbyanvj3x4-clojure-todo-app-built-classes)
1c1
< build/
---
> /nix/store/1ssj6x352q1wp4mpkr20z3kbyanvj3x4-clojure-todo-app-built-classes
```

**Comment by unclechu** [comment]
It seems that 144 of 989 files differ.
``` console
$ for f in $(cd build && find * -type f); do diff "build/$f" "/nix/store/1ssj6x352q1wp4mpkr20z3kbyanvj3x4-clojure-todo-app-built-classes/$f"; done | wc -l
144
$ (cd build && find * -type f) | wc -l
989
```
Not sure if I can rely on Java and/or Clojure compiler to not include timestamps to the class file or whatever.

**Comment by unclechu** [comment]
It seems I can’t rely on that. Two similar builds made one by one differ:
``` console
$ for f in $(cd build && find * -type f); do diff "build/$f" "build2/$f"; done | wc -l
48
```

**Comment by unclechu** [comment]
Something wrong with the isolated build. I used the same JAR files, the same Java version. The only difference is those built class files.

**Comment by unclechu** [comment]
Okay, problem ~~solved~~ identified. Everything is totally fine except that.. I don’t know what? JVM? Closure? Tried to write something to that build directory. `/nix/store/` is not writable mount point. I copied the built class files directory to local dir which is writable and tried to use it. It works fine:
``` console
$ cp -r /nix/store/1ssj6x352q1wp4mpkr20z3kbyanvj3x4-clojure-todo-app-built-classes build-test
$ java -cp "$(find deps-as-jars/ | xargs | tr ' ' ':')":build-test clojure_todo_app.main
Running HTTP server on port 8080…
```

``` console
$ curl http://localhost:8080
hello world
```

**Comment by unclechu** [comment]
I don’t know where to address this issue but I think it’s not a problem of this library. So I’m closing it.

**Comment by unclechu** [comment]
Maybe if I manage to create a JAR file out of it then I wouldn’t have this problem.

**Comment by unclechu** [comment]
# Problem solved

I just created a JAR file out of compiled class files and it worked just fine. Here is a diff:

``` diff
diff --git a/default.nix b/default.nix
index 0e4755c..af0fd9f 100644
--- a/default.nix
+++ b/default.nix
@@ -70,7 +70,7 @@ let
   ];
 
   backendBuiltClasses = pkgs.stdenv.mkDerivation {
-    name = "${name}-built-classes";
+    name = "${name}-backend-build.jar";
     src = backendSrc;
 
     nativeBuildInputs = [
@@ -103,14 +103,18 @@ let
             clojure.lang.Compile \
             "$module"
         done
+
+        cd build
+        CLASS_FILES=$(find * -name '*.class')
+        readarray -t CLASS_FILES_A <<< "$CLASS_FILES"
+        jar -cf build.jar "''${CLASS_FILES_A[@]}"
       )
 
       eval -- "$checkPhase"
     '';
 
     installPhase = ''
-      mkdir -p -- "$out"
-      cp -r build/* -- "$out"
+      cp -r build/build.jar -- "$out"
     '';
   };
 
@@ -122,7 +126,7 @@ let
     text = ''
       #! ${e.dash}
       exec ${esc e.java} \
-        -cp ${esc backend-classpaths}:${backendBuiltClasses} \
+        -cp ${esc backend-classpaths}:${esc backendBuiltClasses} \
         ${esc backendMainClass} "$@"
     '';
   };
```

See https://github.com/unclechu/clojure-todo-app/commit/62a66568e500964887055eadf946c18d92ffb7f9
